"""
Django settings for assistencia_tecnica_os project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)%!4+bde8c^koax0mn57afs3a_rbceq!q*w&*b6v5#*0ruy33+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# assistencia_tecnica_os/assistencia_tecnica_os/settings.py

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'rest_framework', # <<< Adicione esta linha!
    'corsheaders',
    'app_os.apps.AppOsConfig', # Seu aplicativo personalizado
    # Outros apps personalizados, se houver
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'assistencia_tecnica_os.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'assistencia_tecnica_os.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'assistencia_os_db',                 # O nome do banco de dados que você criou
        'USER': 'django_user',                      # O nome do usuário que você criou
        'PASSWORD': 'gatemnikova22',         # <-- A NOVA SENHA, SÓ COM LETRAS E NÚMEROS!
        'HOST': 'localhost',                        # Onde o PostgreSQL está rodando
        'PORT': '5432',                             # Porta padrão do PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Adicionando a pasta 'static' na raiz do projeto para arquivos estáticos globais
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Usando Path para criar o caminho
]

# O diretório onde `collectstatic` vai copiar todos os arquivos estáticos para produção
STATIC_ROOT = BASE_DIR / 'staticfiles_collected'


# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS (Cross-Origin Resource Sharing) Settings
# Para permitir requisições de domínios específicos (seu frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # <<<<<< SEU ENDEREÇO DO FRONTEND AQUI
    # Se você usar outro endereço (ex: 127.0.0.1:5173), adicione-o também
    # "http://127.0.0.1:5173",
]

# Ou, para permitir TUDO (apenas para desenvolvimento, NUNCA em produção)
# CORS_ALLOW_ALL_ORIGINS = True