# Generated by Django 5.2.3 on 2025-06-17 09:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefone_principal', models.CharField(max_length=20, verbose_name='Telefone Principal')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='PecaCategoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Peça',
                'verbose_name_plural': 'Categorias de Peças',
                'ordering': ['nome_categoria'],
            },
        ),
        migrations.CreateModel(
            name='ServicoPreDefinido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=255, unique=True, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço')),
                ('preco_fixo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Fixo')),
            ],
            options={
                'verbose_name': 'Serviço Pré-Definido',
                'verbose_name_plural': 'Serviços Pré-Definidos',
                'ordering': ['nome_servico'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_equipamento', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('PC_MESA', 'PC de Mesa')], max_length=10, verbose_name='Tipo de Equipamento')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Equipamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='app_os.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['tipo_equipamento', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('EM_REPARO', 'Em Reparo'), ('PRONTO', 'Pronto para Retirada/Entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status da OS')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Técnico')),
                ('servico_realizado', models.TextField(blank=True, null=True, verbose_name='Serviço Realizado')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('observacoes_internas', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='app_os.cliente', verbose_name='Cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='app_os.equipamento', verbose_name='Equipamento')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_peca', models.CharField(max_length=50, unique=True, verbose_name='Código da Peça')),
                ('nome_peca', models.CharField(max_length=255, verbose_name='Nome da Peça')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='app_os.pecacategoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['nome_peca'],
            },
        ),
        migrations.CreateModel(
            name='OS_Peca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_utilizada', models.IntegerField(default=1, verbose_name='Quantidade Utilizada')),
                ('valor_unitario_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (na OS)')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_utilizadas', to='app_os.ordemservico', verbose_name='Ordem de Serviço')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usada_em_os', to='app_os.peca', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'Peça Utilizada na OS',
                'verbose_name_plural': 'Peças Utilizadas na OS',
                'unique_together': {('ordem_servico', 'peca')},
            },
        ),
        migrations.CreateModel(
            name='OS_Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preco_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Cobrado na OS')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_realizados', to='app_os.ordemservico', verbose_name='Ordem de Serviço')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicado_em_os', to='app_os.servicopredefinido', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço Realizado na OS',
                'verbose_name_plural': 'Serviços Realizados na OS',
                'unique_together': {('ordem_servico', 'servico')},
            },
        ),
    ]
